### ISSUE TITLE
Boolean settings are not implemented

### ISSUE THREAD

**Issue by jako4295** [jako4295/crabtype#15]
None of the boolean settings are implemented yet and therefore do not change anything when toggled in settings.

There needs to be implemented the following functionalities for now:
- [x] **capital_letters**: include capital letters in the typing test
- [x] **numbers**: include numbers in the typing test
- [x] **parenthesis**: include different types of parenthesis in the typing test
- [ ] #27
- [ ] #28
    - [ ] **characters per minute** 

It is not yet decided if including more characters should imply that all possible characters are drawn uniformly, if there should be a higher chance of getting a standard letter, or if this should be an option in the settings. As a first implementation, it should probably be whatever is the simplest to implement

**Comment by jako4295** [comment]
Perhaps add an easter egg if all characters are disabled - maybe something like a pre-determined sentence to type - suggestion: "You thought you could disable all settings and still play? How dumb." Or something else creative.

**Comment by jmoerk123** [comment]
Moved the rest to two new issues. The rest is done
